# Generated by Django 3.0.5 on 2020-12-19 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='description',
            field=models.TextField(default='Welcome!', max_length=400),
        ),
    ]
