# Generated by Django 3.0.5 on 2020-12-18 19:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom1', models.CharField(max_length=40)),
                ('symptom2', models.CharField(max_length=40)),
                ('symptom3', models.CharField(max_length=40)),
                ('symptom4', models.CharField(max_length=40)),
                ('ct_scan', models.ImageField(upload_to='report_pics')),
                ('disease_detected', models.CharField(max_length=40)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile')),
            ],
        ),
    ]
