# Generated by Django 3.0.5 on 2020-12-19 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_appointment_chat_hospital_post_speciality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='huser',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='image',
        ),
        migrations.AddField(
            model_name='hospital',
            name='uid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_hospital',
            field=models.BooleanField(default=False),
        ),
    ]
