# Generated by Django 3.0.5 on 2020-12-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201219_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='phone_no',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
    ]
