# Generated by Django 3.1.4 on 2020-12-19 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20201219_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientrecord',
            name='disease_detected',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='symptom1',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
