# Generated by Django 3.1.4 on 2020-12-19 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0008_auto_20201219_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientrecord',
            name='ct_scan',
        ),
        migrations.RemoveField(
            model_name='patientrecord',
            name='xray',
        ),
        migrations.CreateModel(
            name='ScanXRay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xray', models.ImageField(blank=True, null=True, upload_to='report')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScanCT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ct_scan', models.ImageField(blank=True, null=True, upload_to='report')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
